"""
Django settings for SecureFit project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)44udf7385o(nc8$er7&rgfz@)&tg^8sp^(+wii2!*%1ui@_=n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MYAPP',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SecureFit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SecureFit.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JS, Images)
STATIC_URL = 'static/'


# Default primary key field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ===========================================================================
# 🔐 SECURE COOKIE & CSRF SETTINGS (FIXED)
# ===========================================================================

# Cookies will ONLY be sent over HTTPS (prevents theft on public WiFi)
SESSION_COOKIE_SECURE = True

# Cookie cannot be accessed via JavaScript (prevents session hijacking via XSS)
SESSION_COOKIE_HTTPONLY = True

# Cookie is NOT sent in cross-site requests (prevents CSRF attacks)
SESSION_COOKIE_SAMESITE = 'Strict'

# CSRF cookie hardened as well
CSRF_COOKIE_SECURE = True          # Only sent via HTTPS
CSRF_COOKIE_HTTPONLY = True        # Not accessible via JavaScript
CSRF_COOKIE_SAMESITE = 'Strict'    # Blocks cross-site CSRF

# ===========================================================================
# END OF SECURE SETTINGS
# ===========================================================================

