"""
Django settings for SecureFit project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# ----------------------------------------------------------------------
# BASE DIRECTORY
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------------------------
# 🔐 SECRET KEY (In production load from environment variable)
# ----------------------------------------------------------------------
SECRET_KEY = 'django-insecure-)44udf7385o(nc8$er7&rgfz@)&tg^8sp^(+wii2!*%1ui@_=n'


# ----------------------------------------------------------------------
# DEBUG MODE
# ----------------------------------------------------------------------
# For assignment demo we keep DEBUG=True so server runs normally.
# In real deployment, DEBUG must ALWAYS be False.
DEBUG = True


# ----------------------------------------------------------------------
# ALLOWED HOSTS — required when using secure cookie settings
# ----------------------------------------------------------------------
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ----------------------------------------------------------------------
# APPLICATIONS
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'MYAPP',      # Our application
]


# ----------------------------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',   # Manages cookies
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',             # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',# Uses sessionid
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'SecureFit.urls'


# ----------------------------------------------------------------------
# TEMPLATES
# ----------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'SecureFit.wsgi.application'


# ----------------------------------------------------------------------
# DATABASE
# ----------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ----------------------------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ----------------------------------------------------------------------
# INTERNATIONALISATION
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------------------------
# STATIC FILES
# ----------------------------------------------------------------------
STATIC_URL = 'static/'


# ----------------------------------------------------------------------
# PRIMARY KEY FIELD TYPE
# ----------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ======================================================================
# 🔐 SECURE COOKIE & CSRF SETTINGS — FINAL LOCALHOST-COMPATIBLE VERSION
# ======================================================================
# These settings FIX session hijacking & CSRF vulnerabilities.
# They are fully secure while still working on localhost (HTTP).
#
# ✔ Prevents session stealing via XSS      → HttpOnly cookies
# ✔ Prevents CSRF attacks                  → SameSite=Strict
# ✔ Avoids HTTPS-only issues on localhost  → Secure=False for demo
#
# ======================================================================


# -----------------------------
# SESSION COOKIE SECURITY
# -----------------------------

# ❗ HttpOnly prevents JavaScript from reading sessionid.
#    This stops XSS-based session hijacking.
SESSION_COOKIE_HTTPONLY = True

# ❗ Strict prevents cookie being sent in cross-site contexts.
#    This blocks CSRF attacks by default.
SESSION_COOKIE_SAMESITE = 'Strict'

# ❗ Must be False on localhost (otherwise cookie won’t set on HTTP).
#    In real deployment: True (HTTPS only).
SESSION_COOKIE_SECURE = False



# -----------------------------
# CSRF COOKIE SECURITY
# -----------------------------

# ❗ Hides CSRF cookie from JavaScript (stops token theft).
CSRF_COOKIE_HTTPONLY = True

# ❗ Prevents CSRF from cross-site POST requests.
CSRF_COOKIE_SAMESITE = 'Strict'

# ❗ Must be False on localhost; True only in production.
CSRF_COOKIE_SECURE = False


# ======================================================================
# END OF SECURE SETTINGS
# ======================================================================
